DECLARE @FileName nvarchar(500) = N'C:\SQLBackups\QatFarmDb_' + CONVERT(varchar(8), GETDATE(), 112) + N'.bak';
BACKUP DATABASE [QatFarmDb]
TO DISK = @FileName
WITH INIT, COMPRESSION, CHECKSUM, STATS = 10;
RESTORE VERIFYONLY FROM DISK = @FileName WITH CHECKSUM;
